spring:
  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true

# CORS (frontend em dom√≠nio separado)
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:}
    extra-origins: ${CORS_EXTRA_ORIGINS:}
  storage:
    type: cloudinary
    cloudinary:
      cloud-name: ${CLOUDINARY_CLOUD_NAME}
      api-key: ${CLOUDINARY_API_KEY}
      api-secret: ${CLOUDINARY_API_SECRET}
      folder: aqui
